<?php
/* $Id$ */

/**
 * Todo list
 * 1. In filter, should be able to set size and other details. ESPECIALLY start location, (for load failure)
 * 3. Make it so they're not shown if in teaser mode (maybe)
 * 4. Clean up table - remove many things from it. Style it better
 */

/**
 * Valid permissions for this module
 * @return array An array of valid permissions for the module
 */

function tripinfo_menu() {

  $items['tripinfo'] = array(
    'title' => 'Hobobiker Trip Details',
    'page callback' => 'tripinfo_list',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  $items['tripinfo_item'] = array(
    'page callback' => 'tripinfo_item',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  $items['loadnode'] = array(
    'page callback' => 'tripinfo_loadnode',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
  $items['mappage'] = array(
    'page callback' => 'tripinfo_mappage',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  return $items;
}


function validate_date($date) {
  list($y, $m, $d) = split('-', $date, 3);
  return sprintf("%04d-%02d-%02d", $y, $m, $d);
}

function tripinfo_list($startdate, $enddate) {
  $startdate = validate_date($startdate);
  $enddate = validate_date($enddate);

  $page_content .= '<div >';

  $page_content .= "<h4>$startdate to $enddate</h4>";

  $page_content .= t("<div>
		Here is detailed information about our trip. For each day's
		ride we have a map, gpx and kml files, and an elevation profile.<br/><br/>
		If you find that this isn't up-to-date or you want something that's
		not here, please send us an email and we'll try to get it for you.
		</div>");


  $page_content .= tripinfo_table($startdate, $enddate);
  $page_content .= "</div>";

  return $page_content;
}


function tripinfo_gmap($kmlfile) {
  $google_map_location = "https://maps.googleapis.com/maps/api/js?key=" . variable_get('googlemap_api_key', '0');
  drupal_set_html_head("<script src='$google_map_location'  type='text/javascript'></script>");

  drupal_add_js(drupal_get_path('module', 'tripinfo') . "/tripinfo_filtermap.js");


  $output .= "<div style='height:500px;width:100%'><div class='mapholder' id='mapholder' style='width:100%;height:100%'>
	 <div class='filtermap' id='filtermap' style='width:100%;height:100%;border:2px solid black'></div>";

  $settings['tripinfo'] = array('kmlfile' => $kmlfile);
  drupal_add_js($settings, 'setting');

  $output .= l("Explore in Google Earth", $kmlfile) . "</div></div>";

  return $output;
}


function tripinfo_item($date, $startdate, $enddate) {
  $date = validate_date($date);
  $startdate = validate_date($startdate);
  $enddate = validate_date($enddate);

  list($year, $month, $day) = split("-", $date);

  $date_sqlformat = $date . "T00:00:00";
  $query = "select body, field_date_value date, month(field_date_value) month,
	    day(field_date_value) day, year(field_date_value) year, field_start_value start,
		field_destination_value destination, field_miles_value miles,
		field_elevation_gain_value ElevGain, field_camp_or_hotel_value
		from
		content_type_triplog t, node_revisions r

		where r.nid = t.nid and r.vid = t.vid
		and field_date_value = '%s'";


  $sth = db_query($query, $date_sqlformat);
  if (!$sth) {
    drupal_set_message('Failed to run query; information in system log.');
    watchdog(WATCHDOG_ERROR, 'Failed to run query %query', $query);
    return;
  }

  $row = db_fetch_object($sth);


  $fulldate = sprintf("%04d%02d%02d", $row->year, $row->month, $row->day);

  $gpxfname = "files/gps/$fulldate.gpx";
  $kmlfname = "files/gps/$fulldate.kml";
  $profile_fname = "files/gps/$fulldate.png";
  $kmlurl = "/$kmlfname";

  $whentime = mktime(12, 0, 0, $row->month, $row->day, $row->year);
  $when = strftime("%B %d, %Y", $whentime);

  $page .= ($tripinfo_nav = tripinfo_navigation($date, $startdate, $enddate));

  $page .= "<h3>$when: $row->start to $row->destination</h3>";

  if (file_exists($kmlfname)) {
    $page .= tripinfo_gmap($kmlurl);
  }

  $page .= "<div class=\"tripdesc\" style='margin-top: 60px; border-top: 2px solid black;'><i>$row->body</i></div>";

  $page .= "<ul>";
  $km = round($row->miles / .62);
  $meters = round($row->ElevGain / 3.24);
  $page .= "<li>$row->miles miles/$km kilometers</li>";
  $page .= "<li><a href='#profile'>Elevation Gain: $row->ElevGain feet/$meters meters</a></li>";
  $page .= "<li>Where we stayed: $row->field_camp_or_hotel_value</li>";
  if (file_exists($gpxfname)) {
    $page .= "<li><a href=\"/$gpxfname\">Download GPX file</a></li>";
  }
  if (file_exists($kmlfname)) {
    $page .= "<li><a href=\"/$kmlfname\">Download KML file</a></li>";
  }

  $page .= "</ul>";

  if (file_exists($profile_fname)) {
    $page .= "<hr /><a name='profile'><h4>Elevation Profile</h4></a>";
    $page .= "<img id='elevation_profile' src=\"/$profile_fname\">";

  }

  $page .= $tripinfo_nav;

  return $page;
}

function tripinfo_table($startdate, $enddate) {

  $query = "select field_date_value date, month(field_date_value) month,
	    day(field_date_value) day, year(field_date_value) year, field_start_value start,
		field_destination_value destination, field_miles_value miles,
		field_elevation_gain_value ElevGain, field_camp_or_hotel_value 'Where stayed'
		from content_type_triplog
		where field_date_value >= '%s' and field_date_value <= '%s'
		and field_miles_value <> 0 order by field_date_value asc";

  $page .= "<table class='tripinfo_table_table'>\n";
  $page .= "<tr><th>Ride</th><th>date</th><th>miles/km</th>
		<th>Elev ft/mt</th></tr>\n";

  $sth = db_query($query, $startdate, $enddate);
  if (!$sth) {
    drupal_set_message('Failed to run query; information in system log.');
    watchdog(WATCHDOG_ERROR, 'Failed to run query %query', $query);
    return;
  }

  while ($row = db_fetch_object($sth)) {

    $fulldate = sprintf("%04d%02d%02d", $row->year, $row->month, $row->day);

    $date = sprintf("%04d-%02d-%02d", $row->year, $row->month, $row->day);
    $location = $row->location;
    $miles = $row->miles;
    $elevgain = $row->ElevGain;
    $page .= "<tr>";

    $page .= "<th scope='row'>" . l("$row->start to $row->destination",
      "tripinfo_item/$date/$startdate/$enddate") . "</th>";
    $page .= "<td>$date</td>";

    $km = round($row->miles / .62);
    $elevgainmt = round($row->ElevGain / 3.24);
    $page .= "<td>$row->miles/$km</td><td>$row->ElevGain/$elevgainmt</td>";
    $page .= "</tr>";
  }
  $page .= "</table>";

  return $page;
}


function tripinfo_filter($op, $delta = 0, $format = -1, $text = '') {
  switch ($op) {
    case 'list':
      return array(0 => 'Multiple-source Google Map (multisource)');
    case 'description':
      return t('Create a google map from multiple XML or GEOrss sources. Use "multisource:http:...,http://..."');
    case 'settings':
      break;
    case 'no cache':
      return FALSE; // debugging only
    case 'prepare':
      return $text;
    case 'process':
      return tripinfo_filter_gmap($format, $text);
    default:
      return $text;
  }

}

function tripinfo_filter_gmap($format, $text) {
  $text = preg_replace_callback('/\[multisource:(.+?)\]/', 'tripinfo_gen_gmap', $text);

  return $text;
}

function tripinfo_gen_gmap($text) {

  $overlays = $text[1];
  $kmlfile = preg_replace('/,.*$/', '', $overlays);

  $google_map_location = "https://maps.googleapis.com/maps/api/js?key=" . variable_get('googlemap_api_key', '0');

  $output .= <<<ENDOUTPUT
<?php
  drupal_set_html_head("<script src='$google_map_location'  type='text/javascript'></script>");
  drupal_add_js(drupal_get_path('module', 'tripinfo') . "/tripinfo_filtermap.js");
  \$settings['tripinfo'] = array('kmlfile' => '$kmlfile');
  drupal_add_js(\$settings, 'setting');
?>
ENDOUTPUT;

  $output .= "<div style='height:500px;width:100%'><div class='mapholder' id='mapholder' style='width:100%;height:100%'>
	 <div class='filtermap' id='filtermap' style='width:100%;height:100%;border:2px solid black'></div>";

  $output .= l("Explore in Google Earth", $kmlfile) . "</div></div><br/><br/>";

  return $output;
}

function tripinfo_navigation($date, $startdate, $enddate) {
  $output = '';
  $links = '';

  if ($date) {

    if ($prev = tripinfo_item_prev($date)) {
      $links .=
        l('‹ ' . $prev->title, "tripinfo_item/$prev->item/$startdate/$enddate",
          array(
            'attributes' => array(
              'class' => 'page-previous',
              'title' => t('Go to previous page')
            )
          ));
    }
    if ($startdate) {
      $links .=
        l(t('Up'), "tripinfo/$startdate/$enddate", array(
          'attributes' => array(
            'class' => 'page-up',
            'title' => t('Go back to list')
          )
        ));
    }
    if ($next = tripinfo_item_next($date)) {
      $links .=
        l($next->title . ' ›', "tripinfo_item/$next->item/$startdate/$enddate",
          array(
            'attributes' => array(
              'class' => 'page-next',
              'title' => t('Go to next page')
            )
          ));
    }

    if (isset($links)) {
      $output = '<div class="book-navigation">';
      if (isset($tree)) {
        $output .= $tree;
      }
      if (isset($links)) {
        $output .= '<div class="page-links clear-block">' . $links . '</div>';
      }
      $output .= '</div>';
    }
  }

  return $output;
}

function tripinfo_item_prev($date) {
  $prevdate = db_fetch_object(db_query(
    'select left(field_date_value,10) item, field_start_value start,field_destination_value dest from content_type_triplog t
	   where t.field_date_value < "%s" order by field_date_value desc limit 1',
    $date . "T00:00:00"));
  $prevdate->title = "$prevdate->start to $prevdate->dest";
  return $prevdate;
}

function tripinfo_item_next($date) {
  $nextdate = db_fetch_object(db_query(
    'select left(field_date_value,10) item,field_start_value start,field_destination_value dest from content_type_triplog t
	   where t.field_date_value > "%s" order by field_date_value asc limit 1',
    $date . "T00:00:00"));
  $nextdate->title = "$nextdate->start to $nextdate->dest";
  return $nextdate;

}

