<?php

/**
 * @file
 * Provides install, updated, and uninstall functions for recaptcha_mailhide.
 */

/**
 * Issue #2473329: Remove obsolete variables.
 */
function recaptcha_mailhide_update_6100() {
  $ret = array();

  // recaptcha_mailhide no longer uses any variables.
  db_query("DELETE FROM {variable} WHERE name LIKE '%s'", 'recaptcha_mailhide_%');
  cache_clear_all('variables', 'cache');
  $ret[] = array('success' => TRUE, 'query' => 'Removed obsolete variables.');

  return $ret;
}
